import Cocoa

// MARK: - ClipboardManager (Polling)
final class ClipboardManager {
    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private let vault: ClipboardHubStore

    init(vault: ClipboardHubStore) {
        self.vault = vault
    }
    
    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.checkClipboard()
        }
    }
    
    func stop() {
        timer?.invalidate()
        timer = nil
    }
    
    /// Marks that password managers and other apps put on what shouldn't be kept in a history (nspasteboard.org)
    private static let privateTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    private func checkClipboard() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        // The history is stored unencrypted, so a copied password never goes in it
        if let types = pb.types, !Self.privateTypes.isDisjoint(with: types) { return }

        let frontmost = NSWorkspace.shared.frontmostApplication
        let bundleID = frontmost?.bundleIdentifier
        let appName = frontmost?.localizedName
        
        if let image = pb.readObjects(forClasses: [NSImage.self], options: nil)?.first as? NSImage {
            if let tiff = image.tiffRepresentation, let bitmap = NSBitmapImageRep(data: tiff) {
                let pngData = bitmap.representation(using: .png, properties: [:])
                Task { @MainActor in
                    vault.addItem(content: "[Image]", type: IslandClipItem.ItemType.image, sourceBundleID: bundleID, sourceAppName: appName, imageData: pngData)
                }
            }
            return
        }
        
        if let string = pb.string(forType: .string), !string.isEmpty {
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            let type = detectType(trimmed)
            
            Task { @MainActor in
                vault.addItem(content: trimmed, type: type, sourceBundleID: bundleID, sourceAppName: appName, imageData: nil)
            }
        }
    }
    
    private func detectType(_ content: String) -> IslandClipItem.ItemType {
        if let url = URL(string: content), url.scheme != nil { return IslandClipItem.ItemType.url }
        let codeMarkers = ["{", "}", ";", "func ", "let ", "var ", "import", "class"]
        if codeMarkers.contains(where: { content.contains($0) }) { return IslandClipItem.ItemType.code }
        return IslandClipItem.ItemType.text
    }
}
